export const CHANGE_NAME = 'CHANGE_NAME'
export const INIT_CLIENTS = 'INIT_CLIENTS'
export const ON_CLIENT_SELECT = 'ON_CLIENT_SELECT'
export const INIT_MEASUREMENTTYPES = 'INIT_MEASUREMENTTYPES'

export const ON_LOGIN = 'ON_LOGIN'
export const ON_LOGOUT = 'ON_LOGOUT'
